### ISSUE TITLE
Can not display image of study when running the latest version of OHIF/Viewers( v5.0.0-v2-sprint-1)

### ISSUE THREAD

**Issue by thanhtd1012** [knopkem/dicomweb-proxy#15]
Hi @knopkem!

Before I used your dicomweb-proxy to run OHIF/Viewers(v4.5.12)
It worked correctly.

Hovewer, I upgrade OHIF/Viewers to the latest version of OHIF/Viewers( v5.0.0-v2-sprint-1).
It is not working.

I got the error when when running the latest version of OHIF/Viewers( v5.0.0-v2-sprint-1):
Cannot GET /viewer/rs/studies/1.2.840.114257.42904.2015122104032215890/series/1.2.840.114257.42904.2015122104032215890.1/instances/1.2.840.114257.42904.2015122104032215890.1.1.1/frames/1

Please check and help me!

Can you check it and help me the solution ?
Thank you so much!

**Comment by knopkem** [comment]
Hi,
please note that the latest release of OHIF is 4.8.6. I just updated the repo to include this build version which (using my fix that never got merged) still works.

v5 is a testing branch and apparently there are still some bugs. Running yarn dev against their own dcm4chee archive fails:

![ohif](https://user-images.githubusercontent.com/994526/106167872-f5f9bd80-618d-11eb-9342-76d4ad2e24e9.PNG)

The error you showed indicates that wadouri is now even more broken than before (wadouri should not access individual frames, this is a wadors behavior, thus the proxy doesn't provide this route).

If you want to test the latest version I would suggest to use [dicomweb-pacs](https://github.com/knopkem/dicomweb-pacs). This handles the frame route (but I have no idea if it works with v5)

**Comment by knopkem** [comment]
I just tested it with dicomweb-pacs and could get it to work at least to the point where I get the same issue as above.
Try the branch "experimental"

**Comment by knopkem** [comment]
Ahh, wait I tested the v5 with my modifications (needed for wadouri before) and apparently this doesn't work anymore. So when using dicomweb-pacs (defaulting to wadors) it works now. I updated the experimental package.
If there is time I will check into wado-uri (for dicomweb-proxy)

**Comment by knopkem** [comment]
ok, I just gave it a try and it worked! Apparently OHIF finally fixed the wadouri issue (so my patch is not needed here as well).
I could not use the umd package so switched to the progressive build but that seems to work. 
I pushed it to "experimental" branch in this repo.
Note: keycloak has been removed to simplify testing. Let me know if it works for you too.

**Comment by thanhtd1012** [comment]
Oke! I got it!
I will follow it!
Let you know if it work too.

Thank you so much!

**Comment by thanhtd1012** [comment]
Hi @knopkem!
Could you tell me the difference between dicomweb-proxy and dicomweb-pacs?
Could  I use dicomweb-pacs instead of dicomweb-proxy?

Thank you so much!

**Comment by knopkem** [comment]
Hello,
the dicomweb-proxy is a proxy between a dicomweb ready image viewer (e.g. the ohif viewer, but not limited to it) and any standard complient PACS archive (e.g. DCM4CHEE, Orthanc, Conquest, siemens, GE pacs etc.). Basically what it does: it translates DICOM network messages to DICOMWEB messages. It can only use wadouri as it is limited by the metadata the DICOM messages provide (c-find results). Wadouri is less performant than wadors and OHIF disables some functionality if this is used (e.g. MPR)

The dicomweb-pacs projects doesn't use this proxy step but rather is a PACS itself while at the same time providing a direct interface to dicomweb. This way it has access to all the metadata and can provide wadors (default) as well as wadouri. It is similar to DCM4CHEE v5 (arc-light) but the PACS archive is very basic and only uses sql-light as storage database. However the goal is to be able to set it up in seconds (while installing DCM4CHEE is still a pain, without using docker).

Let me know if you have more questions.

**Comment by thanhtd1012** [comment]
Oke! Thanks!

I tried  your dicomweb-proxy at  "experimental" branch in this repo.

Hoverwer, it is still not working when running the latest version of OHIF/Viewers( v5.0.0-v2-sprint-1):

I got the error 
Cannot GET /viewer/rs/studies/1.2.840.114257.42904.2015122104032215890/series/1.2.840.114257.42904.2015122104032215890.1/instances/1.2.840.114257.42904.2015122104032215890.1.1.1/frames/1

And I checked console.log, get the error below
 Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Please check and help me!
Could you tell me about how to you corrected!
Thank you so much!

**Comment by knopkem** [comment]
From the error it is clear that you use the ohif viewer with a wrong config. By default when compiling ohif yourself the config will use wadors. Thus make sure to use the correct 'app-config.js' file that sets wadouri for image and thumbnail rendering.

```
window.config = {
  routerBasename: '/',
  // whiteLabelling: {},
  extensions: [],
  modes: [],
  showStudyList: true,
  // filterQueryParam: false,
  dataSources: [
    {
      friendlyName: 'DICOMWeb Server',
      namespace: 'org.ohif.default.dataSourcesModule.dicomweb',
      sourceName: 'dicomweb',
      configuration: {
        name: 'DICOMWEB_PACS',
        wadoUriRoot: 'wadouri',
        qidoRoot: 'rs',
        wadoRoot: 'rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    },
  ],
  defaultDataSourceName: 'dicomweb',
};
```

Btw. the 'experimental' branch contains the precompiled v5 version, just try with this first. Also make sure to delete your browser cache before.

**Comment by thanhtd1012** [comment]
Hi @knopkem!
I got it!
I tried it. It is worked correctly!
Thank you so much!
