### ISSUE TITLE
CMOVE STORE complain error

### ISSUE THREAD

**Issue by zhan2016** [knopkem/dicomweb-proxy#23]
Hello, Thanks for your hard work. It's amazing. Nowadays I'm testing to use dicomwebproxy with GE PACS with usecget setting to false. After viewing some studies, the OHIF viewer complains below and never work well except restart dicomwebproxy. 
**The error from ohif:**
![OHIF](https://user-images.githubusercontent.com/20983133/114263108-37bca500-9a16-11eb-9e94-b2d4da58c172.png)
**The error from dicomwebproxy's server console:**
![console](https://user-images.githubusercontent.com/20983133/114263119-528f1980-9a16-11eb-9bdc-c2c040b1308b.png)
**The error from GEPACS's console:**
![GEPACS](https://user-images.githubusercontent.com/20983133/114263132-689cda00-9a16-11eb-8075-c911c5450ea2.png)

I'm sure there aren't some special configurations on GE endpoint.  This eror will occur after sometimes' image viewer. And everthing  works well when dicomwebproxy start refresh or reboot.

**Comment by knopkem** [comment]
Hi and thanks. The error from GE helped to pinpoint the problem and indeed there was a default setting (max associations) which was set too low. I pushed a fix to the dicom-dimse-native plugin. So make sure to update the dependencies of the dicomweb-proxy (dicom-dimse-native should be v1.2.13) and please try again. Let me know if this fixes the issue for you. Cheers

**Comment by zhan2016** [comment]
Thanks for your update. It solves max association problem perfectly. Another theree problems occurs:
**timeout in non-blocking mode:**
This error will generate cmove failed. The dicomwebproxy console print as below:
![image](https://user-images.githubusercontent.com/20983133/114289965-73a34900-9aae-11eb-92e1-e6a2863a6ff8.png)
**After some ohif studies viewer, some file read write error occurs:**
![image](https://user-images.githubusercontent.com/20983133/114289992-b36a3080-9aae-11eb-9015-485227046585.png)
**sometimes write local db failed:**
![image](https://user-images.githubusercontent.com/20983133/114290013-d563b300-9aae-11eb-9d29-95960c670c92.png)
 
at the same time, ohif viewer will go to suck and never go well again:
![image](https://user-images.githubusercontent.com/20983133/114290111-ac8fed80-9aaf-11eb-91ea-c02e64f1f4f2.png)
 
everything goes well as soon as dicomwebproxy start a while or reboot. And errors will occur after program run some time.

**Comment by knopkem** [comment]
Hi, I updated the version with some fixes, please try again. Thanks.

**Comment by zhan2016** [comment]
Thanks for your update. I just test it. But It also failed after some studies had been opened on ohif viewer. 
**The GE Console complain:**
![image](https://user-images.githubusercontent.com/20983133/114401836-de02d900-9bd5-11eb-8195-9fab00b45074.png)
**The DicomwebProxy Complain:**
![image](https://user-images.githubusercontent.com/20983133/114401938-f1ae3f80-9bd5-11eb-8b60-1f91f45ab421.png)
**The ohif viewer:**
![image](https://user-images.githubusercontent.com/20983133/114401998-012d8880-9bd6-11eb-85ee-1d2e2a056bd1.png)
**My package-lock.json:**
![image](https://user-images.githubusercontent.com/20983133/114402665-a3e60700-9bd6-11eb-9d87-698fc148797d.png)

**Why is the max association still a question?What's more,program will never go well after errors occur except rebooting it.**

**Comment by zhan2016** [comment]
Maybe more different CT studies have more chance to reproduce these bugs.

**Comment by knopkem** [comment]
I will need to try to reproduce this using a bigger repository.
The max association issue should imho only appear if more than 128 associations (connections to the PACS) are open (previously this was set to16). This could happen if you try to quickly open lots of studies with multiple series (one association per series) and slow network (or contention). I didn't disable the option as since the server is threaded (not using processes) it will crash at one point (thread stack overflow). I'll make this an options.
The main issue I see with the proxy is, that it's easy to flood it with requests (just open a study go back open another study) and no cancel is in place (however, cancel requests are often badly supported by PACS from my experience) or some other way to manage this.
Did you see timeout issues again? Normally this should not happen and associations should be kept pending forever now (which is not ideal). I'll also make the timeout a setting (it was 60s before).
You could also try to enable 'verboseLogging' and see if this gives some more interesting output.

**Comment by zhan2016** [comment]
Yes, Blocking time out issues disappear! Your description is very accuate!
`The max association issue should imho only appear if more than 128 associations (connections to the PACS) are open (previously this was set to16). This could happen if you try to quickly open lots of studies with multiple series (one association per series) and slow network (or contention).  `

**Comment by zhan2016** [comment]
> I will need to try to reproduce this using a bigger repository.
> The max association issue should imho only appear if more than 128 associations (connections to the PACS) are open (previously this was set to16). This could happen if you try to quickly open lots of studies with multiple series (one association per series) and slow network (or contention). I didn't disable the option as since the server is threaded (not using processes) it will crash at one point (thread stack overflow). I'll make this an options.
> The main issue I see with the proxy is, that it's easy to flood it with requests (just open a study go back open another study) and no cancel is in place (however, cancel requests are often badly supported by PACS from my experience) or some other way to manage this.
> Did you see timeout issues again? Normally this should not happen and associations should be kept pending forever now (which is not ideal). I'll also make the timeout a setting (it was 60s before).
> You could also try to enable 'verboseLogging' and see if this gives some more interesting output.

Hello，I’m still stuck on it. The proxy is easy to flood it with requests.Do you make some progress?

**Comment by knopkem** [comment]
Hi, I tried to reproduce with a local PACS and many studies but could not reach the point where it fails. I guess I would need to simulate slow network for this.
One thing I thought of and that I would suggest we could try is to use image level queries instead of series. This way each request would only fetch one image and be done very quickly. Of course this is normally a bit slower than fetching everything at once but worth a try. What do you think?
Hadn't have the time to add the new option (to set max associations ) but I guess this would only shift the problem.

**Comment by knopkem** [comment]
I pushed some changes (v.1.1.3) to the proxy to allow specifying other query levels beside the default (SERIES). So you can try with 'STUDY' or 'IMAGE'. Unfortunately the OHIF viewer seems to prefetch all images in a series which has the opposite effect of what I described before: it will spawn more associations and likely case issues even earlier, maybe fetching on STUDY level helps. Best to try both. 
Note: For the moment fetching on Study/Series level has the effect that the viewer doesn't show any images until all data is local, I'm about to change this but this will take more time.
Other than that I will add the option to increase the max-association number in a next version.

**Comment by zhan2016** [comment]
Thank you very much.I’ll try it and give feedback.

**Comment by knopkem** [comment]
I think I found a better solution for the flooding. When using the latest master you should have a new config option maxAssociations (defaults to 4) in the default.cfg. This should make sure that no more than e.g. 4 concurrent associations are made (so this is different to the max-association option in dcmtk).

**Comment by knopkem** [comment]
any news?

**Comment by zhan2016** [comment]
Sorry for later reply. Problem still exits. Max associations configure item
and three query retrieve levels also not work.
problem still：
This could happen if you try to quickly open lots of studies with multiple
series (one association per series) and slow network (or contention).
------------------------------
发自我的iPhone


------------------ Original ------------------
*From:* Michael Knopke ***@***.***>
*Date:* Sun,May 2,2021 4:17 PM
*To:* knopkem/dicomweb-proxy ***@***.***>
*Cc:* zhan2016 ***@***.***>, Author ***@***.***>
*Subject:* Re: [knopkem/dicomweb-proxy] CMOVE STORE complain error (#23)

any news?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/knopkem/dicomweb-proxy/issues/23#issuecomment-830770223>,
or unsubscribe

**Comment by knopkem** [comment]
That's weird, wouldn't have thought that even with a low max-assoc number this issue would still happen.
The only explanation would be that somehow association release doesn't work and so it still counts the jobs that were already finished.
Without being able to reproduce I'm not sure what to change now. I suggest that you set retrieve level to 'SERIES', max-associations to 1 and verboseLogging to true. Now you should be able to see the linear flow of events (1 request per time) no matter how many studies you open. You should see the messages regarding association negotiation and releasing. This might give a clue why it happens.
